# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.26.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
x=np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [11]:
print(x.itemsize,
x.size)

8 10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
y=np.array(list(range(10,50)))

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [26]:
y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
np.random.randint(2,10, size=(3,3))

array([[5, 7, 6],
       [8, 6, 3],
       [3, 2, 6]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [31]:
a=np.array([1,2,0,0,4,0])
np.where(a!=0)


(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [42]:
np.random.rand(3,3,3)

array([[[0.72756965, 0.81679258, 0.51232049],
        [0.54160624, 0.25170003, 0.83716055],
        [0.66236274, 0.83844931, 0.85538084]],

       [[0.70913898, 0.33061446, 0.71331602],
        [0.78217933, 0.45597448, 0.7157743 ],
        [0.05700289, 0.61510726, 0.39972176]],

       [[0.29269848, 0.87166802, 0.51662756],
        [0.59753765, 0.26851008, 0.6995681 ],
        [0.8670546 , 0.6924695 , 0.07807305]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [48]:
b=np.random.rand(10,10)
print(np.max(b),
np.min(b))

0.971612062777469 0.016825846186890203


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [52]:
c=np.array(list(range(30))).mean()
c

14.5

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [73]:
a=np.ones((5,6))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [75]:
a[0],a[-1]=0,0
a[:,0:1], a[:,-1]=0,0
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [81]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [91]:

np.diag(np.arange(1, 5),k=-2)


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [105]:
x=np.zeros((8,8))
x[::2,::2]=1
x[1::2,1::2 ]=1
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [110]:

np.random.rand(6, 7, 8)
np.unravel_index(99,(6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [116]:
import numpy as np

# Create a 2x2 array representing a single checkerboard square
checkerboard_square = np.array([[0, 1],
                                [1, 0]])

# Tile the checkerboard square to create the 8x8 checkerboard matrix
checkerboard = np.tile(checkerboard_square, (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [121]:
r=np.random.rand(5,5)
min_value = np.min(r)
max_value = np.max(r)
norm= (r-min_value)/(max_value-min_value)
norm

array([[0.53561932, 0.1779314 , 0.80353284, 0.12044299, 0.99688156],
       [0.3921645 , 0.97857299, 0.6669972 , 1.        , 0.44741274],
       [0.03041788, 0.71183187, 0.1071569 , 0.39397955, 0.49796127],
       [0.40526902, 0.67232856, 0.6827794 , 0.11876918, 0.59526375],
       [0.91663504, 0.        , 0.55011473, 0.6676229 , 0.51830413]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [122]:
import numpy as np


color_dtype = np.dtype([('R', np.uint8),   # Red channel
                        ('G', np.uint8),   # Green channel
                        ('B', np.uint8),   # Blue channel
                        ('A', np.uint8)])  # Alpha channel


example_color = np.array((255, 128, 0, 255), dtype=color_dtype)

print("Custom dtype for RGBA color:")
print(color_dtype)
print("\nExample color (RGBA):")
print(example_color)


Custom dtype for RGBA color:
[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]

Example color (RGBA):
(255, 128, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [130]:
a=np.random.rand(5,3)
b=np.random.rand(3,2)
c=np.dot(a,b)
c

array([[1.12828261, 0.2052152 ],
       [0.49778904, 0.37232923],
       [0.54794666, 0.69209027],
       [1.39785469, 0.9786873 ],
       [0.45868894, 0.23331692]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [139]:
a=np.array(list(range(1,20)))
a[(a>3) & (a<8)] *= -1
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [140]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# So, the legal expressions are:

# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [143]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\gnana\AppData\Local\Temp\ipykernel_12248\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\gnana\AppData\Local\Temp\ipykernel_12248\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\gnana\AppData\Local\Temp\ipykernel_12248\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [3]:
import numpy as np
Z = np.random.uniform(-10,+10,10)
print(np.ceil(Z))

[-2.  8.  4. -4.  9. -9.  3. -0.  8.  8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [7]:
a=np.array([1,2,3,4])
b=np.array([11,2,13,4])
np.intersect1d(a,b)

array([2, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [8]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [9]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [15]:
y=np.datetime64('today','D')- np.timedelta64(1,'D')
print(y,
np.datetime64('today','D')
,np.datetime64('today','D')+np.timedelta64(1,'D'))

2024-02-24 2024-02-25 2024-02-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [16]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [21]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [27]:
z=np.random.uniform(0,10,5)

np.floor(z)
z.astype(int)
z//1
z - z%1
np.trunc(Z)

array([-2.,  7.,  3., -4.,  8., -9.,  2., -0.,  7.,  7.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [32]:
np.tile(np.arange(0, 5), (5,1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [34]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [50]:
np.linspace(0, 1, 10, endpoint=False)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [56]:
a=np.random.random(10)
a.sort()
print(a)


[0.04774537 0.13119884 0.20757257 0.23705439 0.33291744 0.46333271
 0.51311861 0.75506929 0.85034948 0.88044297]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [58]:
z=np.arange(10)
np.add.reduce(Z)

5.0

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [62]:
a=np.array([1,5,4])
b=np.array([2,5,4])
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [65]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [69]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.7780499  0.06185076 0.97911811 1.04902635 0.90463107 0.94714512
 1.21182231 0.73202815 0.7854028  0.70583023]
[0.70867166 0.26662371 1.08198185 0.77617498 0.32117789 0.03001372
 0.71188834 0.40157631 0.05773103 0.24660456]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [79]:
z=np.random.random(10)
z[z.argmax()] = 0
z

array([0.80181095, 0.23420787, 0.47896927, 0.        , 0.56879393,
       0.7897135 , 0.1867285 , 0.84925866, 0.12217537, 0.21779394])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [81]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [82]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [83]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [84]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [85]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

70
